name: Deploy pages

on:
    push:
        branches:
            -   master
    pull_request:
        branches:
            -   master
jobs:
    deploy:
        runs-on: macos-latest
        permissions:
            contents: write
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0        
            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./src